import { CurrencyCode, CurrencyRate } from './types';

export const INITIAL_RATES: CurrencyRate[] = [
  { code: CurrencyCode.USD, name: 'US Dollar', flag: '🇺🇸', buy: 1600, sell: 1615 },
  { code: CurrencyCode.GBP, name: 'British Pound', flag: '🇬🇧', buy: 2050, sell: 2080 },
  { code: CurrencyCode.EUR, name: 'Euro', flag: '🇪🇺', buy: 1720, sell: 1750 },
  { code: CurrencyCode.CAD, name: 'Canadian Dollar', flag: '🇨🇦', buy: 1150, sell: 1180 },
  { code: CurrencyCode.AUD, name: 'Australian Dollar', flag: '🇦🇺', buy: 1050, sell: 1080 },
  { code: CurrencyCode.CNY, name: 'Chinese Yuan', flag: '🇨🇳', buy: 220, sell: 235 },
  { code: CurrencyCode.AED, name: 'UAE Dirham', flag: '🇦🇪', buy: 430, sell: 445 },
  { code: CurrencyCode.SAR, name: 'Saudi Riyal', flag: '🇸🇦', buy: 420, sell: 435 },
  { code: CurrencyCode.CHF, name: 'Swiss Franc', flag: '🇨🇭', buy: 1750, sell: 1780 },
  { code: CurrencyCode.JPY, name: 'Japanese Yen', flag: '🇯🇵', buy: 10.5, sell: 11.5 },
  { code: CurrencyCode.ZAR, name: 'South African Rand', flag: '🇿🇦', buy: 85, sell: 95 },
  { code: CurrencyCode.GHS, name: 'Ghanaian Cedi', flag: '🇬🇭', buy: 95, sell: 105 },
  { code: CurrencyCode.INR, name: 'Indian Rupee', flag: '🇮🇳', buy: 18, sell: 20 },
  { code: CurrencyCode.XOF, name: 'CFA Franc', flag: '🇧🇯', buy: 2.4, sell: 2.8 },
  { code: CurrencyCode.KES, name: 'Kenyan Shilling', flag: '🇰🇪', buy: 12, sell: 13 },
  { code: CurrencyCode.SGD, name: 'Singapore Dollar', flag: '🇸🇬', buy: 1180, sell: 1210 },
  { code: CurrencyCode.TRY, name: 'Turkish Lira', flag: '🇹🇷', buy: 45, sell: 48 },
  { code: CurrencyCode.BRL, name: 'Brazilian Real', flag: '🇧🇷', buy: 280, sell: 300 },
  { code: CurrencyCode.KRW, name: 'South Korean Won', flag: '🇰🇷', buy: 1.1, sell: 1.3 },
  { code: CurrencyCode.MYR, name: 'Malaysian Ringgit', flag: '🇲🇾', buy: 350, sell: 370 },
  { code: CurrencyCode.SEK, name: 'Swedish Krona', flag: '🇸🇪', buy: 150, sell: 160 },
  { code: CurrencyCode.NOK, name: 'Norwegian Krone', flag: '🇳🇴', buy: 150, sell: 162 },
  { code: CurrencyCode.DKK, name: 'Danish Krone', flag: '🇩🇰', buy: 235, sell: 250 },
  { code: CurrencyCode.PLN, name: 'Polish Zloty', flag: '🇵🇱', buy: 420, sell: 440 },
  { code: CurrencyCode.MXN, name: 'Mexican Peso', flag: '🇲🇽', buy: 92, sell: 98 },
  { code: CurrencyCode.NZD, name: 'New Zealand Dollar', flag: '🇳🇿', buy: 960, sell: 990 },
  { code: CurrencyCode.HKD, name: 'Hong Kong Dollar', flag: '🇭🇰', buy: 200, sell: 210 },
  { code: CurrencyCode.TWD, name: 'New Taiwan Dollar', flag: '🇹🇼', buy: 48, sell: 52 },
  { code: CurrencyCode.THB, name: 'Thai Baht', flag: '🇹🇭', buy: 43, sell: 46 },
  { code: CurrencyCode.IDR, name: 'Indonesian Rupiah', flag: '🇮🇩', buy: 0.09, sell: 0.11 },
  { code: CurrencyCode.PHP, name: 'Philippine Peso', flag: '🇵🇭', buy: 28, sell: 31 },
  { code: CurrencyCode.VND, name: 'Vietnamese Dong', flag: '🇻🇳', buy: 0.05, sell: 0.06 },
  { code: CurrencyCode.PKR, name: 'Pakistani Rupee', flag: '🇵🇰', buy: 5.5, sell: 6.2 },
  { code: CurrencyCode.BDT, name: 'Bangladeshi Taka', flag: '🇧🇩', buy: 14, sell: 15.5 },
  { code: CurrencyCode.LKR, name: 'Sri Lankan Rupee', flag: '🇱🇰', buy: 4.8, sell: 5.5 },
  { code: CurrencyCode.NPR, name: 'Nepalese Rupee', flag: '🇳🇵', buy: 11, sell: 12.5 },
  { code: CurrencyCode.RUB, name: 'Russian Ruble', flag: '🇷🇺', buy: 17, sell: 19 },
  { code: CurrencyCode.UAH, name: 'Ukrainian Hryvnia', flag: '🇺🇦', buy: 42, sell: 46 },
  { code: CurrencyCode.CZK, name: 'Czech Koruna', flag: '🇨🇿', buy: 66, sell: 72 },
  { code: CurrencyCode.HUF, name: 'Hungarian Forint', flag: '🇭🇺', buy: 4.2, sell: 4.9 },
  { code: CurrencyCode.RON, name: 'Romanian Leu', flag: '🇷🇴', buy: 340, sell: 365 },
  { code: CurrencyCode.BGN, name: 'Bulgarian Lev', flag: '🇧🇬', buy: 860, sell: 900 },
  { code: CurrencyCode.ISK, name: 'Icelandic Krona', flag: '🇮🇸', buy: 11, sell: 12.5 },
  { code: CurrencyCode.ARS, name: 'Argentine Peso', flag: '🇦🇷', buy: 1.8, sell: 2.3 },
  { code: CurrencyCode.CLP, name: 'Chilean Peso', flag: '🇨🇱', buy: 1.6, sell: 2.0 },
  { code: CurrencyCode.COP, name: 'Colombian Peso', flag: '🇨🇴', buy: 0.38, sell: 0.48 },
  { code: CurrencyCode.PEN, name: 'Peruvian Sol', flag: '🇵🇪', buy: 420, sell: 445 },
  { code: CurrencyCode.XAF, name: 'CFA Franc (Central)', flag: '🇨🇲', buy: 2.4, sell: 2.8 },
  { code: CurrencyCode.UGX, name: 'Ugandan Shilling', flag: '🇺🇬', buy: 0.41, sell: 0.5 },
  { code: CurrencyCode.TZS, name: 'Tanzanian Shilling', flag: '🇹🇿', buy: 0.55, sell: 0.65 },
  { code: CurrencyCode.EGP, name: 'Egyptian Pound', flag: '🇪🇬', buy: 50, sell: 55 },
  { code: CurrencyCode.MAD, name: 'Moroccan Dirham', flag: '🇲🇦', buy: 155, sell: 170 },
  { code: CurrencyCode.TND, name: 'Tunisian Dinar', flag: '🇹🇳', buy: 500, sell: 540 },
  { code: CurrencyCode.DZD, name: 'Algerian Dinar', flag: '🇩🇿', buy: 11, sell: 12.5 },
  { code: CurrencyCode.ETB, name: 'Ethiopian Birr', flag: '🇪🇹', buy: 28, sell: 32 },
  { code: CurrencyCode.ILS, name: 'Israeli New Shekel', flag: '🇮🇱', buy: 420, sell: 450 },
  { code: CurrencyCode.QAR, name: 'Qatari Riyal', flag: '🇶🇦', buy: 430, sell: 450 },
  { code: CurrencyCode.KWD, name: 'Kuwaiti Dinar', flag: '🇰🇼', buy: 5150, sell: 5350 },
  { code: CurrencyCode.BHD, name: 'Bahraini Dinar', flag: '🇧🇭', buy: 4180, sell: 4350 },
  { code: CurrencyCode.OMR, name: 'Omani Rial', flag: '🇴🇲', buy: 4100, sell: 4300 },
];

export const APP_NAME = "NairaWatch";
